### ISSUE TITLE
CI tests

### ISSUE THREAD

**Issue by anthonyshort** [Jam3/hihat#31]
I can't seem to figure out a nice way to just use hihat to run tape tests on Travis. How are people doing this sort of thing?

**Comment by anthonyshort** [comment]
Using `tape-run` works, but I really don't want to add more modules just to run it in CI:

```
browserify test/index.js -t babelify | tape-run
```

Plus this in `.travis.yml`

```
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
```
